### ISSUE TITLE
Error: C stack usage  10847362 is too close to the limit

### ISSUE THREAD

**Issue by Carota-1** [sartorlab/methylSig#50]
I got an error "Error: C stack usage  10847362 is too close to the limit" when I run 23 sample by 
"bsseq_stranded = read.bismark(
  files = files,
  colData = data.frame(row.names = c("WT56","WT57","WT58","MU63","MU67","WT68","WT75","MU76","MU80","WT89","MU96","MU97","WT01","WT10","MU13","WT19","MU827","WT837","WT850","WT856","WT867","MU880","MU894")),
  rmZeroCov = FALSE,
  strandCollapse = TRUE,nThread=1
)"
How can I resolve it?

**Comment by rcavalcante** [comment]
Hi,

I'm not sure this is a methylSig problem so much as a system problem. Have you looked at this thread on Stack Exchange (https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit)?

I would suggest asked on the Bioconductor forums, and specifically tagging the bsseq package. MethylSig doesn't have a read function, but uses the bsseq::read.bismark() function instead. When posting, I'd suggest giving an idea of the size of your data, and giving your sessionInfo().

I would also recommend taking a look at the parameters available in that function here: https://bioconductor.org/packages/release/bioc/manuals/bsseq/man/bsseq.pdf

For now, since this isn't particularly a methylSig problem, I'm going to close this issue.

Raymond
